# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yL-MQjIdf3JVV-utNPrnIkQX9sZi286L
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/Expanded_data_with_more_features.csv")
print(df.head())

df.head()

df.describe()

df.info()

df.isnull().sum()

df=df.drop("Unnamed: 0", axis=1)
print(df.head())

df["WklyStudyHours"]=df["WklyStudyHours"].str.replace("05-Oct","5-10")
df.head()

plt.figure(figsize=(5,5))
ax=sns.countplot(data=df,x="Gender",palette={"male": "orange", "female": "blue"})
ax.bar_label(ax.containers[0])
plt.title("Gender Distribution")
plt.show()

gb=df.groupby("ParentEduc").agg({"MathScore":'mean', "ReadingScore":'mean', "WritingScore":'mean'})
print(gb)

plt.figure(figsize=(4,4))
sns.heatmap(gb,annot=True,cmap="viridis")
plt.title("Parent's Education vs Student's Score")
plt.show()

gb1=df.groupby("ParentMaritalStatus").agg({"MathScore":'mean', "ReadingScore":'mean', "WritingScore":'mean'})
print(gb1)

plt.figure(figsize=(4,4))
sns.heatmap(gb1,annot=True,cmap="hot")
plt.title("Parent's Marital Status vs Student's Score")
plt.show()

sns.boxplot(data=df, x="MathScore")
plt.show()

sns.boxplot(data=df, x="ReadingScore")
plt.show()

sns.boxplot(data=df, x="WritingScore")
plt.show()

print(df["EthnicGroup"].unique())

groupA = df.loc[(df["EthnicGroup"] == "group A")].count()
groupB = df.loc[(df["EthnicGroup"] == "group B")].count()
groupC = df.loc[(df["EthnicGroup"] == "group C")].count()
groupD = df.loc[(df["EthnicGroup"] == "group D")].count()
groupE = df.loc[(df["EthnicGroup"] == "group E")].count()
l=["group A","group B","group C","group D","group E"]
mlist=[groupA["EthnicGroup"], groupB["EthnicGroup"], groupC["EthnicGroup"], groupD["EthnicGroup"], groupE["EthnicGroup"]]
plt.pie(mlist, labels=l, autopct='%1.2f%%')
print(mlist)
plt.title("Ethnic Group Distribution")
plt.show()

ax=sns.countplot(data=df,x="EthnicGroup",palette={"group A": "orange", "group B": "blue","group C":"red","group D":"green","group E":"yellow"})
ax.bar_label(ax.containers[0])
plt.title("Ethnic Group Distribution")
plt.show()